import Head from 'next/head'

const posts = [
  {title: "React testing", excerpt:   "Learn React testing"},
  {title: "React with Tailwind", excerpt: "Learn React with Tailwind"}
];

export default function Home() {
  return (
    <div className='container mx-auto px-10 mb-8 bg-gray-300'>
      <Head>
        <title>Blog-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        {posts.map((post, index) => (
          <div>
            {post.title}
            {post.excerpt}
          </div>
        ))}
      </div>
    </div>
  )
}
