import Head from 'next/head'

import { PostCard, PostWidget, Categories, Header } from "../components";

import { getPosts } from '../services';


export default function Home({posts}) {
  return (
    <>
      <Header />
      <div className='container mx-auto px-10 mb-8'>
        <Head>
          <title>Blog-App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
          <div className='container mx-auto px-0 mb-10 lg:col-span-8 col-span-1'>
            {posts.map((post, index) => (
              <PostCard key={index} post={post.node} />
            ))}
          </div>
          <div className='lg:col-span-4 col-span-1'>
              <div className='lg:sticky relative top-8'>
                <PostWidget />
                <Categories />
              </div>
          </div>
        </div>
      </div>
    </>  
  )
}

// Fetch data at build time
export async function getStaticProps() {

  const posts = (await getPosts()) || [];
  
  return {
    props: { posts },
  };
}